Completed task4 from lesson4
osamuking/KotlinSprint pull request #26
Opened 2023-04-05 10:44 UTC by osamuking

Ох, наворочено что-то с этой задачей... Вот такой вариант подойдет?

2023-04-06 03:26 UTC, ievetrov requested changes

2023-04-06 03:26 UTC, ievetrov commented on src/main/kotlin/Lesson4/lesson4_task4.kt
> +    val abs = day == 1 || day == 9 || day == 11
Видимо сформулировано немного сложновато:

> Программа тренировок разбивает упражнения на несколько групп: упражнения для мышц рук, ног, спины и пресса. Она рекомендует делать упражнения на каждую группу мышц через день. Пользователь начал занятия с рук и пресса. Напиши программу, которая будет сообщать, какие упражнения нужно выполнить сегодня. 

1 день - руки+пресс
2 день - спина+ноги
3 день - руки+пресс
4 день - спина+ноги

Таким образом есть тренировки по четным и нечетным дням, как понять что число четное ты уже знаешь )

2023-04-06 03:26 UTC, ievetrov commented on src/main/kotlin/Lesson4/lesson4_task4.kt
> +    val abs = day == 1 || day == 9 || day == 11
Но если интересно, как решить кейс когда следующий день - отдых:
```Kotlin
     val day = readln().toInt()
     val arms = day == 1 || day == 5 || day == 9
     val abs  = day == 1 || day == 5 || day == 9
     val legs = day == 3 || day == 7 || day == 11
     val back = day == 3 || day == 7 || day == 11  
    
     // или, если не ограничивать day
     val arms = day % 4 == 1
     val abs  = day % 4 == 1
     val legs = day % 4 == 3 
     val back = day % 4 == 3 
```

2023-04-07 03:11 UTC, osamuking commented on src/main/kotlin/Lesson4/lesson4_task4.kt
> +    val abs = day == 1 || day == 9 || day == 11
Изменил код, теперь вроде как надо работает. Комментарии хочу оставить - потом буду пользоватся может быть.

2023-04-07 16:38 UTC, ievetrov approved these changes

2023-04-07 18:52 UTC, merged