Completed task5 from lesson5
osamuking/KotlinSprint pull request #34
Opened 2023-04-08 12:50 UTC by osamuking

2023-04-09 11:03 UTC, ievetrov requested changes

2023-04-09 11:03 UTC, ievetrov commented on src/main/kotlin/Lesson5/lesson5_task4.kt
> +        if ((input1 != input2) && ((input1 == number1 || input1 == number2) &&
мне кажется, что рандомные выйгрышные числа могут выпасть и одинаковыми. а тут проверка на нераверство

2023-04-09 13:17 UTC, osamuking commented on src/main/kotlin/Lesson5/lesson5_task4.kt
> +        if ((input1 != input2) && ((input1 == number1 || input1 == number2) &&
Да, действительно, зачем-то я эту проверку сюда вставил... Удаляю

2023-04-10 13:05 UTC, ievetrov approved these changes

2023-04-10 13:08 UTC, merged