Completed task1 from lesson7
osamuking/KotlinSprint pull request #44
Opened 2023-04-17 06:35 UTC by osamuking

2023-04-17 20:35 UTC, ievetrov requested changes
финальная строка не формируется в какую-то одну конкретную переменную (цель не просто вывести в консоль, а представить готовую строку. в теории с ней могут контактировать далее другие компоненты программы

2023-04-18 21:28 UTC, ievetrov approved these changes

2023-04-18 21:28 UTC, ievetrov commented on src/main/kotlin/Lesson7/lesson7_task1.kt
> +    var symbol1 = '1'
ок, но не было требований инициализировать некий другой код

2023-04-18 23:26 UTC, osamuking commented on src/main/kotlin/Lesson7/lesson7_task1.kt
> +    var symbol1 = '1'
Переделал. Сначала не догадался, что можно всё в цикл засунуть.

2023-04-18 23:27 UTC, merged