KS1-5 Completed task5 from lesson1
osamuking/KotlinSprint pull request #5
Opened 2023-03-30 23:13 UTC by osamuking

2023-03-31 05:58 UTC, ievetrov requested changes

2023-03-31 05:58 UTC, ievetrov commented on src/main/kotlin/Lesson1/lesson1_task5.kt
> +    val flightMinutes = 108
Да, корректно. Но давай разгружать человеческий процессор и нагружать железный ))
Вместо вычисления в уме, напиши тут код осуществляющий преобразование

2023-03-31 05:58 UTC, ievetrov commented on src/main/kotlin/Lesson1/lesson1_task5.kt
> +    println("$flightMinutes:00")
И давай сделаем твой код универсальным.
Если бы нам пришли новые данные, и оказалось что полет занят 6485 секунд, переменная поменялась, а у тебя будут по прежнему печататься 00

2023-03-31 22:07 UTC, osamuking commented on src/main/kotlin/Lesson1/lesson1_task5.kt
> +    println("$flightMinutes:00")
Скорее всего существуют какие-то изящные решения, но мне сие пока не ведомо. Так и не придумал - как сделать так, чтобы секунды  в случае однозначного числа выводились с нулём впереди.

2023-04-01 18:15 UTC, ievetrov requested changes

2023-04-01 18:15 UTC, ievetrov commented on src/main/kotlin/Lesson1/lesson1_task5.kt
> +    var sec = (60 * (flightMinutes - min)).toInt()
Давай такой пример:
100 минут - это 1 час и 40 минут
100 / 60 = 1 и остаток 40.
В Котлин есть оператор нахождения остатка от деления: %
```Kotlin
println(100 % 60) // выведет 40
```

Попробуй с этими знаниями решить задачку еще раз

2023-04-01 22:23 UTC, ievetrov requested changes

2023-04-01 22:23 UTC, ievetrov commented on src/main/kotlin/Lesson1/lesson1_task5.kt
> +    var flightMinutes = flightSeconds/60
между операторами и операндами принято добавлять пробел:
```Kotlin
flightSeconds / 60
```

2023-04-01 22:23 UTC, ievetrov commented on src/main/kotlin/Lesson1/lesson1_task5.kt
> +    var sec = flightSeconds%60
да, теперь верно. Только нужны пробелы вокруг %, так лучше читается

2023-04-01 22:23 UTC, ievetrov commented on src/main/kotlin/Lesson1/lesson1_task5.kt
> +    //как сделать вывод секунд двумя цифрами? Я только (забегая вперед) через
Ноль перед цифрой секунд называют leading zero ( **0**0:**0**0 ).
Без if можно решить при помощи параметров форматирования, пример:
```Kotlin
println("%02d".format(9))
```

2023-04-01 22:37 UTC, osamuking commented on src/main/kotlin/Lesson1/lesson1_task5.kt
> +    //как сделать вывод секунд двумя цифрами? Я только (забегая вперед) через
Хмм.... ну с этим еще разбираться нужно. Пока оставил как есть.

2023-04-02 07:26 UTC, ievetrov requested changes

2023-04-02 07:26 UTC, ievetrov commented on src/main/kotlin/Lesson1/lesson1_task5.kt
> +    //как сделать вывод секунд двумя цифрами? Я только (забегая вперед) через
Тогда удали комменты про то что не знаешь как сделать,
они никак не улучшают читаемость

2023-04-02 11:58 UTC, ievetrov approved these changes

2023-04-02 11:59 UTC, ievetrov commented
Напоминаю, задачки можно сдавать по несколько штук за раз, отправляя несколько Пул реквестов )

2023-04-02 12:00 UTC, merged