Complete task3 from lesson9
osamuking/KotlinSprint pull request #56
Opened 2023-05-01 12:01 UTC by osamuking

2023-05-02 12:30 UTC, ievetrov requested changes

2023-05-02 12:30 UTC, ievetrov commented on src/main/kotlin/Lesson9/lesson9_task3.kt
> +    var omelet = mutableListOf<Int>(2, 50, 15)
тут достаточно неизменяемой переменной (всегда стараемся писать по умолчанию val)

2023-05-02 12:30 UTC, ievetrov commented on src/main/kotlin/Lesson9/lesson9_task3.kt
> +    println("For $numberOfPerson persons you need: Eggs - ${omelet2[0]}, Milk - ${omelet2[1]}, Butter -" +
Тут два комментария:
- в целом код задачи выглядит немного скомканно, не хватает пустых разделяющих строк. хотя бы перед финальным принтом
- если в параметрах аргументы занимают больше одной строки (а в функции println строку в круглых скобках мы и считаем параметром), то эти самые круглые скобки открываются и закрываются на отдельных строках (см. как будет выглядеть код после автоформатирования)

2023-05-02 12:42 UTC, osamuking commented on src/main/kotlin/Lesson9/lesson9_task3.kt
> +    println("For $numberOfPerson persons you need: Eggs - ${omelet2[0]}, Milk - ${omelet2[1]}, Butter -" +
Автоформатирование не захотело ставить круглые скобки на отдельные строки. Пришлось применить силу...

2023-05-03 23:04 UTC, ievetrov approved these changes
ок!

2023-05-03 23:50 UTC, merged