Complete task5 from lesson9
osamuking/KotlinSprint pull request #58
Opened 2023-05-05 23:28 UTC by osamuking

2023-05-06 21:40 UTC, ievetrov requested changes

2023-05-06 21:40 UTC, ievetrov commented on src/main/kotlin/Lesson9/lesson9_task5.kt
> + return string.replaceFirstChar {
а давай тут еще короче форму записи функции применим. без фигурных скобок и без ключевого слова return

2023-05-06 21:40 UTC, ievetrov commented on src/main/kotlin/Lesson9/lesson9_task5.kt
> +    while (i <= 5) {
напоминаю, когда нам известно количество итераций, лучше всего использовать цикл for

2023-05-06 21:40 UTC, ievetrov commented on src/main/kotlin/Lesson9/lesson9_task5.kt
> +fun makeTheFirstLetterHuge(string: String): String {
мне кажется можно переименовать чуть лаконичнее с сохранением смысла. например, capitalizeFirstLetter

2023-05-06 22:22 UTC, osamuking commented on src/main/kotlin/Lesson9/lesson9_task5.kt
> +fun makeTheFirstLetterHuge(string: String): String {
Да это я баловался ))

2023-05-07 01:32 UTC, osamuking commented on src/main/kotlin/Lesson9/lesson9_task5.kt
> +    while (i <= 5) {
Так.... а как заставить цикл for начинать отсчет сначала? Если просто пропускать дубли, то в результате в списке может оказаться всего один элемент (если повторять одно и то же 5 раз). В цикле while это легко обойти с помощью continue, а в for я что-то не могу додуматься - как и дублей избежать и список из 5 элементов сделать.

2023-05-07 13:06 UTC, ievetrov commented on src/main/kotlin/Lesson9/lesson9_task5.kt
> +    while (i <= 5) {
Сначала обратимся к условию. А по условию мы запрашиваем 5 элементов. То есть если все будут дубли и запишется один элемент это тоже норм. 

А вот как вычистить список от дублей это другой вопрос. Какая коллекция не умеет хранить повторы?)

2023-05-07 13:25 UTC, ievetrov requested changes
отписал коммент

2023-05-07 22:03 UTC, osamuking commented on src/main/kotlin/Lesson9/lesson9_task5.kt
> +    while (i <= 5) {
Тогда мне ничего править не надо. Сейчас код выдает список без дублей. Или надо с помощью Set делать?

2023-05-08 00:18 UTC, osamuking commented on src/main/kotlin/Lesson9/lesson9_task5.kt
> +    while (i <= 5) {
В общем попробовал, НО...
Получается, что Set автоматически удаляет повторы, если их добавить?
Использовал sorted, но не понял - почему Идея суёт sorted вместо sort?

2023-05-08 11:30 UTC, ievetrov commented on src/main/kotlin/Lesson9/lesson9_task5.kt
> +    while (i <= 5) {
все верно, надо использовать Set

sorted - это функция-расширение для коллекций, которая возвращает новый список, содержащий отсортированные элементы исходной коллекции. Она не модифицирует исходную коллекцию.

sort - это функция-расширение только для MutableList, которая сортирует элементы списка внутри самого списка. Она не создает новую коллекцию, а изменяет исходный список

2023-05-08 11:33 UTC, ievetrov approved these changes
все корректно)

2023-05-08 20:44 UTC, merged