Completed task1 from lesson10
osamuking/KotlinSprint pull request #59
Opened 2023-05-07 12:19 UTC by osamuking

2023-05-07 19:21 UTC, ievetrov requested changes

2023-05-07 19:21 UTC, ievetrov commented on src/main/kotlin/Lesson10/lesson10_task1.kt
> +fun humanRolls(): Int {
разделение функций бросков не имеет смысла, потому что у них один и тот же функционал. а это уже повторение кода. правильнее будет создать единую универсальную функцию)

2023-05-07 22:03 UTC, osamuking commented on src/main/kotlin/Lesson10/lesson10_task1.kt
> +fun humanRolls(): Int {
Упс... верно )

2023-05-08 11:34 UTC, ievetrov requested changes
> – бросок костей вынеси в отдельную функцию, в которой генерируются
>  2 случайных числа от 1 до 6;

2023-05-09 13:03 UTC, ievetrov approved these changes

2023-05-09 20:48 UTC, merged