Completed task2 from lesson10
osamuking/KotlinSprint pull request #60
Opened 2023-05-11 01:09 UTC by osamuking

2023-05-12 00:08 UTC, ievetrov requested changes

2023-05-12 00:08 UTC, ievetrov commented on src/main/kotlin/Lesson10/lesson10_task2.kt
> +    while (checkLength(pass) < 4) {
функция только возвращает длину пароля (хотя называется проверка длины). нужна валидация внутри функции и возвращаемое соответствующее значение

2023-05-12 00:08 UTC, ievetrov commented on src/main/kotlin/Lesson10/lesson10_task2.kt
> +fun checkLength(x: String): Int {
неочевидное название переменной х

2023-05-12 01:04 UTC, osamuking commented on src/main/kotlin/Lesson10/lesson10_task2.kt
> +    while (checkLength(pass) < 4) {
Не понял, что значит "нужна валидация внутри функции". Может со словом "валидация" затык? Ратификация, утверждение, проверка достоверности, обоснование. Что из этого списка значений имеется в виду? Я так думаю, что по-русски это должно звучать "нужна проверка внутри функции", так? Но и сейчас у меня функция проверяет длину списка и возвращает эту длину.

2023-05-12 14:26 UTC, ievetrov commented on src/main/kotlin/Lesson10/lesson10_task2.kt
> +    while (checkLength(pass) < 4) {
обратимся к условию)

> – проверку длины логина или пароля вынеси в отдельную функцию, которая валидирует длину пароля;

все верно, проверка должна осуществляться внутри функции) то есть мы не размазываем логику, а полностью наделяем функцию проверкой, чтобы она возвращала только лишь true/false

2023-05-12 14:27 UTC, ievetrov requested changes
отписал коммент)

2023-05-13 03:21 UTC, osamuking commented
Попробовал сделать вот так. Но это же не по условию задания получается. Так же, как и в задании с тренировками. Ну, в общем, как сделал, так сделал. Жду ответа верховного судьи )

2023-05-13 19:59 UTC, ievetrov approved these changes
отлично) все легально, а в чем расхождение с условием?)

2023-05-13 21:09 UTC, osamuking commented
Да шут его знает))  Мутно как-то. Ведь для того, чтобы вернуть значение длины пароля, нужно сначала проверить эту самую длину, что и делала моя функция. Ну или я неправильно понимаю значение выражения "проверить длину"...

2023-05-13 21:09 UTC, merged