Guess I completed task4 from lesson10
osamuking/KotlinSprint pull request #62
Opened 2023-05-14 23:24 UTC by osamuking

2023-05-16 09:52 UTC, ievetrov requested changes

2023-05-16 09:52 UTC, ievetrov commented on src/main/kotlin/Lesson10/lesson10_task4.kt
> +fun startOver() {
в условии сказано, что должно быть минимум 2 метода. в данном случае перенос все логики из мейна в дополнительный метод не отвечает требованиям) 

сама программа так и должна быть расположена в основном методе. дополнительные функции используются для выноса действий, которые можно переиспользовать. это важно концептуально, чтобы понимать в принципе зачем нужны функции и как их применять. 

тут следует основной каркас программы обратно поместить в мейн. 
вынести в отдельные функции дополнительно можно, например, сравнение результатов и изменение счетчика выйгрышей. и еще логику продолжения или окончания игры. функция будет принимать то, что введет пользователь

2023-05-21 15:21 UTC, ievetrov requested changes

2023-05-21 15:21 UTC, ievetrov commented on src/main/kotlin/Lesson10/lesson10_task4.kt
> +fun startOver(x: String): Boolean {
очень много названий переменных состоящих из одной буквы. их в идеале вообще не должно быть. 

предлагаю для всей программы заменить a,b,x.y на релевантные читаемые названия.

2023-05-21 15:21 UTC, ievetrov commented on src/main/kotlin/Lesson10/lesson10_task4.kt
> +//    var machineWinningRounds = 0
тут и далее. убрать комментированный код, если он не нужен

2023-05-21 15:21 UTC, ievetrov commented on src/main/kotlin/Lesson10/lesson10_task4.kt
> +        if (humanOneRoundPoints > machineOneRoundPoints)
предлагаю вынести сравнение результатов тоже в отдельную функцию. результат будет сравниваться и возвращать Boolean

2023-05-21 22:52 UTC, osamuking commented
Всё исправил, шеф, НО...
1. В данном конкретном случае мне кажется сомнительной необходимость делать отдельную функцию для сравнения результатов.
2. По поводу однобуквенных переменных. Возможно, что в каких-то сложных и запутанных методах лучше называть переменные с учётом того, что они из себя представляют. Но пока мы не продвинулись далеко, я бы вообще заставлял народ использовать буквы (или любые названия, отличающиеся от тех, которые будут потом использоваться при вызове функции), т.к. функция - суть шаблон (ведь это так?), в который потом могут подставляться какие-то значения. И понимание этого, мне кажется, гораздо важнее, чем умение искать слова для названия переменных (это умение вообще к десятому уроку должно уже в привычку войти). А функции здесь простенькие и любой, взглянув на них, поймет о чем тут речь идет. ИМХО.

2023-05-22 18:12 UTC, ievetrov commented
> Всё исправил, шеф, НО...
> 
> 1. В данном конкретном случае мне кажется сомнительной необходимость делать отдельную функцию для сравнения результатов.
> 2. По поводу однобуквенных переменных. Возможно, что в каких-то сложных и запутанных методах лучше называть переменные с учётом того, что они из себя представляют. Но пока мы не продвинулись далеко, я бы вообще заставлял народ использовать буквы (или любые названия, отличающиеся от тех, которые будут потом использоваться при вызове функции), т.к. функция - суть шаблон (ведь это так?), в который потом могут подставляться какие-то значения. И понимание этого, мне кажется, гораздо важнее, чем умение искать слова для названия переменных (это умение вообще к десятому уроку должно уже в привычку войти). А функции здесь простенькие и любой, взглянув на них, поймет о чем тут речь идет. ИМХО.

не совсем любой, уровень у всех разный) какая бы не казалась задача легкой, суть обучения привить правильные привычки. можно писать программы в несколько строк без функций, без форматирования и т д. Но какой тогда толк от обучения. Делать как следует даже для простых вещей  - это может быть дискомфортно, пока это не вошло в привычку. Но если делать это на автоматизме (по привычке), то уже не задумываешься о том, как обозвать переменную или как отформатировать код. Следовательно вообще не тратишь время на обдумывание и быстрее выполняешь задачу.

не говоря уже о том, что придумывание названий для сущностей/классов итд вообще отдельная наука) чтобы было информативно и понятно всей остальной команде разработчиков

2023-05-22 18:12 UTC, ievetrov approved these changes

2023-05-22 20:17 UTC, merged